import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ThemeProvider from "@/providers/theme-provider";
import Footer from "@/components/footer";
import QueryProvider from "@/providers/query-provider";

import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/auth-provider";
import { authOptions } from "@/lib/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*
          <p>Header</p>
          <Link href="/login">Login</Link>
          <Link href="/categories/react">React</Link> 
        */}
        <SessionProvider session={session}>
          <QueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system">
              <div className="flex flex-col justify-between min-h-screen">
                <Header />
                <div className="flex-grow"> {children} </div>
                <pre>Server session: {JSON.stringify(session)}</pre>
                <Footer />
              </div>
            </ThemeProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
